<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-092S62NG" failures="1" tests="1" name="test" time="2.689" errors="0" timestamp="2024-10-23T12:16:03 IST">
  <testcase classname="testcases.TC03_LoginTestDataDriven" name="verifyloginDDf" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: .\demo_project\Test Data\Logintestdata.xlsx (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: .\demo_project\Test Data\Logintestdata.xlsx (The system cannot find the path specified)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.io.FileNotFoundException: .\demo_project\Test Data\Logintestdata.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
at utilities.excelutility.getrowcount(excelutility.java:30)
at utilities.Dataproviders.getdata(Dataproviders.java:17)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginDDf -->
</testsuite> <!-- test -->
